readme: Some formats, and some cute little typos fixes
thautwarm/diojit pull request #25
Opened 2021-02-09 09:00 UTC by anqurvanillapy

* Do some formatting in README
* Fixed some cute little typos

2021-02-09 10:49 UTC, thautwarm requested changes
Specilisation is intended..
We usually use `specialisation` instead of `specialisation` in related scope:
For instance:
https://www.microsoft.com/en-us/research/wp-content/uploads/2016/07/spec-constr.pdf

And many textbooks also use `s` instead of `z`, e.g, John Hatcliff's "Partial Evaluation, Practice and Theory", which is the main source of referenced technology other than julia lang.

2021-02-09 10:50 UTC, thautwarm commented
Formatting looks good to me.

2021-02-11 08:18 UTC, anqurvanillapy commented
😉 Rework is done. Happy new year, Taine!

2021-02-18 07:37 UTC, thautwarm approved these changes

2021-02-18 07:37 UTC, merged